service: scrapper-lambda
custom:
  defaultStage: "dev"
  personalStage: "${env:STACK_NAME}"

provider:
  name: aws
  region: eu-west-2
  stage: ${opt:stage, self:custom.personalStage ,self:custom.defaultStage}
  runtime: nodejs10.x
  environment:
    NODE_PATH: "./:/opt/node_modules"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

layers:
  chromeModule:
    name: chromeModule-${self:provider.stage}
    path: lambda-layers/chrome-layer
    description: "chrome browser module for lambdas"
    compatibleRuntimes:
      - nodejs10.x
    package:
      include:
        - node_modules/**
  commonModule:
    name: commonModule-${self:provider.stage}
    path: lambda-layers/common-module
    description: "contains all common libraries and middleware for lambdas"
    compatibleRuntimes:
      - nodejs10.x
    package:
      include:
        - node_modules/**

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - lambda-layers/**

functions:
  scraper-function:
    name: "scraper-function-${self:provider.stage}"
    memorySize: 2536
    timeout: 30
    environment:
      DEBUG: 0
    handler: scraper-function.handler
    events:
      - http:
          path: /
          method: get
    layers:
      - { Ref: CommonModuleLambdaLayer }
      - { Ref: ChromeModuleLambdaLayer }
<<<<<<< HEAD

resources:
  Resources:
    gsLivestreamsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
        TableName: ${env:LIVESTREAMS_TABLENAME}-${self:provider.stage}
=======
>>>>>>> refactored firebase to seperate file
