service: scrapper-lambda
provider:
  name: aws
  region: eu-west-2
  runtime: nodejs10.x
  environment:
    LIVESTREAMS_TABLENAME: ${env:LIVESTREAMS_TABLENAME}
    NODE_PATH: "./:/opt/node_modules"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

layers:
  chromeModule:
    path: lambda-layers/chrome-layer
    description: "chrome browser module for lambdas"
    compatibleRuntimes:
      - nodejs10.x
    package:
      include:
        - node_modules/**
  commonModule:
    path: lambda-layers/common-module
    description: "contains all common libraries and middleware for lambdas"
    compatibleRuntimes:
      - nodejs10.x
    package:
      include:
        - node_modules/**

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - lambda-layers/**

functions:
  scraper-function:
    memorySize: 2536
    timeout: 30
    handler:
      scraper-function.handler
      # environment:
    #   DEBUG: 0
    events:
      - http:
          path: /
          method: get
    layers:
      - { Ref: CommonModuleLambdaLayer }
      - { Ref: ChromeModuleLambdaLayer }

resources:
  Resources:
    gsLivestreamsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
        TableName: ${env:LIVESTREAMS_TABLENAME}
