service: livestreams-now-backend

custom:
  userStage: ${env:STACK_NAME}
  defaultStage: "dev"

provider:
  name: aws
  region: eu-west-2
  stage: ${opt:stage, self:custom.userStage, self:custom.defaultStage}
  runtime: nodejs10.x
  environment:
    NODE_PATH: "./:/opt/node_modules"
    DB_NAME: gs-livestreams-${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - lambda-layers/**
  include:
    - ./functions/**/*
  individually: true

functions:
  get-livestreams-function:
    memorySize: 2536
    timeout: 30
    environment:
      DEBUG: 0
    handler: lambdas/get-livestreams.handler
    events:
      - http:
          path: /livestreams
          method: get
    layers:
      - ${cf:livestreams-now-backend-layers-dev.CommonModuleLambdaLayerQualifiedArn }
  scraper-function:
    memorySize: 2536
    timeout: 30
    environment:
      DEBUG: 0
    handler: lambdas/scraper-function.handler
    events:
      - http:
          path: /scrape-data
          method: get
          cors: true
    layers:
      - ${cf:livestreams-now-backend-layers-dev.CommonModuleLambdaLayerQualifiedArn }
      - ${cf:livestreams-now-backend-layers-dev.ChromeModuleLambdaLayerQualifiedArn }
